### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by jamesdiao** [jamesdiao/2017-ACMG-penetrance#1]

**Comment by jamesdiao** [comment]
- [ ] Consider computing point estimates for diseases with no variants in the cohort. 

- [ ] Classify variants using MIM rather than by gene. 

- [ ] XML vs. VCF: Try using the ClinVar XML file rather than the VCF (ftp://ftp.ncbi.nlm.nih.gov/pub/clinvar/xml/). 

- [ ] Assertion rankings/stars: Try factoring in the ClinGen ranking system (stars corresponding to #submitters, assertion criteria, expert panel/practice guideline, etc). 

- [x] Account for ACMG guidelines in counts/fraction plots

- [x] Add heatmap visualization to clinvar-over-time plots.

- [x] Handle when current-day clinvar VCFs are not deleted after processing
